version: 0.2

phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run test
      - npm run build
  post_build:
    commands:
      - rm -f build/static/js/*.map
artifacts:
  files:
    - '**/*'
  base-directory: build
